CREATE TABLE RECIPE(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(100),
  PORTIONS INTEGER,
  IMAGE_URL VARCHAR(1000)
  );

CREATE TABLE INGREDIENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  INGREDIENT_NAME VARCHAR(64),
  AMOUNT INT,
  MEASUREMENT VARCHAR(15),
  TIPS VARCHAR(64),
  RECIPE_ID_FK BIGINT,
  FOREIGN KEY (RECIPE_ID_FK) REFERENCES RECIPE(ID) ON DELETE CASCADE
);

CREATE TABLE INSTRUCTION(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RECIPE_STEPS VARCHAR(400),
  RECIPE_ID_FK BIGINT,
  FOREIGN KEY (RECIPE_ID_FK) REFERENCES RECIPE(ID) ON DELETE CASCADE
);

CREATE TABLE DIET(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  IS_VEGETARIAN BOOLEAN,
  IS_VEGAN BOOLEAN,
  IS_LACTOSE_FREE BOOLEAN,
  IS_GLUTEN_FREE BOOLEAN,
  RECIPE_ID_FK BIGINT,
  FOREIGN KEY (RECIPE_ID_FK) REFERENCES RECIPE(ID) ON DELETE CASCADE
);

